// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function BlockPeer(arg1:string):Promise<void>;

export function DeleteChat(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetChats():Promise<Array<models.Chat>>;

export function GetMessages(arg1:string):Promise<Array<models.Message>>;

export function GetOnlinePeers():Promise<Array<models.Peer>>;

export function GetProfile():Promise<models.Profile>;

export function ListBlocked():Promise<Array<string>>;

export function Logout():Promise<void>;

export function MarkChatRead(arg1:string):Promise<void>;

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;

export function ReactToMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Profile>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Message>;

export function SendSignal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SendTyping(arg1:string,arg2:boolean):Promise<void>;

export function StartChatWithPeer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UnblockPeer(arg1:string):Promise<void>;

export function UpdateProfile(arg1:models.Profile):Promise<void>;
