// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManualPeer(arg1) {
  return window['go']['app']['App']['AddManualPeer'](arg1);
}

export function AppVersion() {
  return window['go']['app']['App']['AppVersion']();
}

export function BlockPeer(arg1) {
  return window['go']['app']['App']['BlockPeer'](arg1);
}

export function DeleteChat(arg1) {
  return window['go']['app']['App']['DeleteChat'](arg1);
}

export function DeleteMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteMessage'](arg1, arg2, arg3);
}

export function GetChats() {
  return window['go']['app']['App']['GetChats']();
}

export function GetDataDir() {
  return window['go']['app']['App']['GetDataDir']();
}

export function GetMessages(arg1) {
  return window['go']['app']['App']['GetMessages'](arg1);
}

export function GetOnlinePeers() {
  return window['go']['app']['App']['GetOnlinePeers']();
}

export function GetProfile() {
  return window['go']['app']['App']['GetProfile']();
}

export function ListBlocked() {
  return window['go']['app']['App']['ListBlocked']();
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function MarkChatRead(arg1) {
  return window['go']['app']['App']['MarkChatRead'](arg1);
}

export function NetworkReady() {
  return window['go']['app']['App']['NetworkReady']();
}

export function OpenDataFolder() {
  return window['go']['app']['App']['OpenDataFolder']();
}

export function ReactToMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReactToMessage'](arg1, arg2, arg3);
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function RemoveManualPeer(arg1) {
  return window['go']['app']['App']['RemoveManualPeer'](arg1);
}

export function RestartNetworking() {
  return window['go']['app']['App']['RestartNetworking']();
}

export function SaveMedia(arg1, arg2) {
  return window['go']['app']['App']['SaveMedia'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SendPing(arg1) {
  return window['go']['app']['App']['SendPing'](arg1);
}

export function SendSignal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SendSignal'](arg1, arg2, arg3, arg4, arg5);
}

export function SendTyping(arg1, arg2) {
  return window['go']['app']['App']['SendTyping'](arg1, arg2);
}

export function StartChatWithPeer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StartChatWithPeer'](arg1, arg2, arg3, arg4, arg5);
}

export function UnblockPeer(arg1) {
  return window['go']['app']['App']['UnblockPeer'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['app']['App']['UpdateProfile'](arg1);
}

export function VPNCreate(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['VPNCreate'](arg1, arg2, arg3, arg4);
}

export function VPNJoin(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['VPNJoin'](arg1, arg2, arg3, arg4, arg5);
}

export function VPNJoinByInvite(arg1, arg2, arg3) {
  return window['go']['app']['App']['VPNJoinByInvite'](arg1, arg2, arg3);
}

export function VPNLeave() {
  return window['go']['app']['App']['VPNLeave']();
}

export function VPNStatus() {
  return window['go']['app']['App']['VPNStatus']();
}
