// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {vpn} from '../models';

export function AddManualPeer(arg1:string):Promise<void>;

export function AppVersion():Promise<string>;

export function BlockPeer(arg1:string):Promise<void>;

export function ClearCallLog():Promise<void>;

export function DeleteChat(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportProfile():Promise<string>;

export function GetCallLog():Promise<Array<models.CallEntry>>;

export function GetChats():Promise<Array<models.Chat>>;

export function GetDataDir():Promise<string>;

export function GetMessages(arg1:string):Promise<Array<models.Message>>;

export function GetOnlinePeers():Promise<Array<models.Peer>>;

export function GetProfile():Promise<models.Profile>;

export function ImportProfile():Promise<models.Profile>;

export function ListBlocked():Promise<Array<string>>;

export function LogCall(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:number):Promise<void>;

export function Logout():Promise<void>;

export function MarkChatRead(arg1:string):Promise<void>;

export function NetworkReady():Promise<boolean>;

export function OpenDataFolder():Promise<void>;

export function ReactToMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Profile>;

export function RemoveManualPeer(arg1:string):Promise<void>;

export function RestartNetworking():Promise<void>;

export function SaveMedia(arg1:string,arg2:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Message>;

export function SendPing(arg1:string):Promise<void>;

export function SendSignal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SendTyping(arg1:string,arg2:boolean):Promise<void>;

export function StartChatWithPeer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function UnblockPeer(arg1:string):Promise<void>;

export function UpdateProfile(arg1:models.Profile):Promise<void>;

export function VPNCreate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<vpn.Status>;

export function VPNJoin(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<vpn.Status>;

export function VPNJoinByInvite(arg1:string,arg2:string,arg3:string):Promise<vpn.Status>;

export function VPNLeave():Promise<vpn.Status>;

export function VPNStatus():Promise<vpn.Status>;
